#!/usr/bin/env bash

function svn-logfrom() {
 svn log -r "{$1}:HEAD"
}

function svn-logbyme() {
 svn log -r "{$1}:HEAD" | sed -n '/fcastill/,/-----$/ p'
}

######## cool functions ###########
DEV_DIR="$HOME/dev"
function cdd () {
    cd "$DEV_DIR/$@"
}

function csd() {
   cs "$DEV_DIR/$@"
}

function osx_cleanFileOpener() {
   rm ~/Library/Caches/CloudKit/CloudKitMetadata*;killall cloudd
}

# speed up open new terminal
function osx_cleanLogs() {
  sudo rm -rf /private/var/log/asl/*.asl
}

# cd and then ls
function cs () {
    cd "$@" && ls
}

# mkdir and then cd into it
function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}

source ./_docker