#!/usr/bin/env bash

function svn-logfrom() {
 svn log -r "{$1}:HEAD"
}

function svn-logbyme() {
 svn log -r "{$1}:HEAD" | sed -n '/fcastill/,/-----$/ p'
}

######## cool functions ###########
function cdd () {
    cd "$DEV_DIR/$@"
}

function csd() {
   cs "$DEV_DIR/$@"
}

# cd and then ls
function cs () {
    cd "$@" && ls
}

# autocomplete
if [ -n "$ZSH_VERSION" ]; then
   # assume Zsh
   compctl -/ -W $DEV_DIR cdd
   compctl -/ -W $DEV_DIR csd
fi


# mkdir and then cd into it
function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}

source "$df_DIR/_docker"

if [ "$df_OS_TYPE" = "linux" ]; then
  source "$df_DIR/_osx"
fi